# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x05\x61gent\"\x1f\n\tUserInput\x12\x12\n\nuser_input\x18\x01 \x01(\t\"!\n\rAgentResponse\x12\x10\n\x08response\x18\x01 \x01(\t\",\n\x14\x43\x61pabilitiesResponse\x12\x14\n\x0c\x63\x61pabilities\x18\x01 \x03(\t\"\x07\n\x05\x45mpty2|\n\x0c\x41gentService\x12\x31\n\x07Process\x12\x10.agent.UserInput\x1a\x14.agent.AgentResponse\x12\x39\n\x0c\x43\x61pabilities\x12\x0c.agent.Empty\x1a\x1b.agent.CapabilitiesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERINPUT']._serialized_start=22
  _globals['_USERINPUT']._serialized_end=53
  _globals['_AGENTRESPONSE']._serialized_start=55
  _globals['_AGENTRESPONSE']._serialized_end=88
  _globals['_CAPABILITIESRESPONSE']._serialized_start=90
  _globals['_CAPABILITIESRESPONSE']._serialized_end=134
  _globals['_EMPTY']._serialized_start=136
  _globals['_EMPTY']._serialized_end=143
  _globals['_AGENTSERVICE']._serialized_start=145
  _globals['_AGENTSERVICE']._serialized_end=269
# @@protoc_insertion_point(module_scope)
