agents:
  - name: researcher
    type: default # 사용할 Agent 클래스 (예: DefaultAgent)
    model:
      type: openrouter
      model_name: meta-llama/llama-4-maverick:free
      api_key_env: OPENROUTER_API_KEY
    system_prompt: "You are a helpful research assistant."

  - name: summarizer
    type: default
    model:
      type: openrouter
      model_name: meta-llama/llama-4-maverick:free
      api_key_env: OPENROUTER_API_KEY
    system_prompt: "You are a concise summarizer."

  - name: function_agent
    type: default
    model:
      type: openrouter
      model_name: meta-llama/llama-4-maverick:free
      api_key_env: OPENROUTER_API_KEY
    system_prompt: "You are a smart calculator."
