agents:
  - name: researcher
    type: default # 사용할 Agent 클래스 (예: DefaultAgent)
    model:
      type: openrouter
      model_name: mistralai/mistral-small-3.1-24b-instruct:free
      api_key_env: OPENROUTER_API_KEY
    system_prompt: "You are a helpful research assistant."

  - name: summarizer
    type: default
    model:
      type: openrouter
      model_name: mistralai/mistral-small-3.1-24b-instruct:free

      api_key_env: OPENROUTER_API_KEY
    system_prompt: "You are a concise summarizer."
